#!/usr/bin/env bash
curl -fLo ~/.floggit/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
git clone https://github.com/TamaMcGlinn/floggit.git ~/.local/floggit
ln -s ~/.local/floggit/bin/floggit ~/.local/bin/floggit
~/.local/bin/floggit -c PlugInstall
